- name: "Stop php-fpm service {{ php.version }}"
  systemd: name="php-fpm-{{ php }}" state=stopped enabled=no daemon_reload=yes
  failed_when: false

- file: path="/run/php/{{ php }}" state=absent

- file: path="/opt/phpfarm/inst/sessions/{{ php }}" state=absent

- file: path="/opt/phpfarm/inst/configs/{{ php }}" state=absent

- file: path="/opt/phpfarm/inst/bin/{{ item }}-{{ php }}" state=absent
  with_items:
    - php-cgi
    - php-config
    - phar
    - pyrus
    - php-fpm
    - phpize
    - phpdbg
    - php

- file: path="/opt/phpfarm/inst/php-{{ php }}" state=absent

- file: path="/opt/phpfarm/src/php-{{ php }}" state=absent

- file: path="/opt/phpfarm/src/bzips/php-{{ php }}" state=absent

- file: path="/opt/phpfarm/src/{{ php }}" state=absent

- file: path="/opt/phpfarm/src/bzips/php-{{ php }}.tar.bz2" state=absent

- file: path="/etc/systemd/system/php-fpm-{{ php }}.service" state=absent

- name: just force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- meta: flush_handlers