#- set_fact: installed_php_versions="{{ installed_php_versions|default([]) }} + [ '{{ item|basename|replace('.service', '')|replace('php-fpm-', '') }}' ]"
#  with_fileglob: "/etc/systemd/system/php-fpm-*.service"


- name: get all installed php versions
  shell: find /etc/systemd/system/ -type f -name php-fpm-*.service | sed -e 's/.service//' | sed -e 's/\/etc\/systemd\/system\/php-fpm-//'
  register: installed_php_versions

- debug: msg="{{ installed_php_versions }}"

- set_fact: current_php_versions="{{ current_php_versions|default([]) }} + [ '{{ item.version }}' ]"
  with_items: "{{ php_versions }}"

- name: "Deleting old php versions"
  include_tasks: delete.yml
  with_items: "{{ installed_php_versions }}"
  when: php not in current_php_versions
  loop_control:
    loop_var: php